# THE ULTIMATE PYTHON COURSE , CODE WITH HARRY    ( 100 VIDEOS WAALI PLAYLIST ) :::



# COVER THESE THING THAT I NOT COVER IN APNA COLLEGE AND GREATLEARNING VIDEOS


print("hello world")
print(5)
print(19*12)

